_target_: src.data.streamable.StreamModule
train_path: /global/cfs/cdirs/m4958/usr/ssaha/JetSSL-Lite/inputs/train_100M_part1_combined.h5
val_path: /global/cfs/cdirs/m4958/usr/ssaha/JetSSL-Lite/inputs/val_5M_combined.h5
#Change this, this is just for testing
test_path: /global/cfs/cdirs/m4958/usr/ssaha/JetSSL-Lite/inputs/TTBar_test_combined.h5
num_csts : 64
n_classes: 10
num_workers: 8
batch_size: 1000
pin_memory: True
transforms:
  - _target_: src.data.preprocessing.preprocess_batch
    _partial_: True
    cst_fn:
      _target_: joblib.load
      filename: ${root_dir}/resources/cst_quantiles_${datamodule.num_csts}.joblib
    jet_fn:
      _target_: joblib.load
      filename: ${root_dir}/resources/jet_quantiles_${datamodule.num_csts}.joblib
